Repository sprint4-team10/Rolling, pull requests merged in 2024-02, with the labels that each got.

#17 ✨ [유경] feat : Post페이지 구현 (컴포넌트 분리X) #16
  src/App.jsx
  src/pages/Post.jsx
  src/pages/PostPage/component/ColorBox.js
  src/pages/PostPage/index.jsx
Labels: 기능, 페이지

#33 ✨ [유경] feat : FONTS파일로 font 크기 지정 #32
  src/pages/PostPage/index.jsx
  src/utils/Fonts.js
Labels: 스타일, 설정

#36 ✨ [유경] feat : MessageCard 컴포넌트 제작 및 적용 #11
  src/pages/compononts/CardList/index.jsx
  src/pages/compononts/CreateCircleButton/ButtonIcon.js
  src/pages/compononts/CreateCircleButton/index.jsx
  src/pages/compononts/MessageCard/MessageCard.jsx
Labels: 컴포넌트

#39 ✨ [유경] feat : buttons 컴포넌트 생성 및 nav바 적용
  src/components/Buttons/Buttons.jsx
  src/components/Buttons/ButtonsStyled.js
  src/components/Buttons/index.js
  src/components/CreateButton/CreateBtn.js
  src/components/CreateButton/index.jsx
  src/components/Navbar.jsx
Labels: 컴포넌트, 스타일

#50 ♻️ [승아] refactor: 불필요한 파일 삭제 및 rem수치 조정 #46
  src/components/RelationshipBadge/RelationshipBadge.jsx
  src/components/RelationshipBadge/index.js
  src/pages/compononts/MessageCard/MessageCard.jsx
Labels: 컴포넌트

#58 ✨ [유경] feat : ArrowButton 컴포넌트 생성 #18
  src/components/Buttons/AddButton/AddButton.jsx
  src/components/Buttons/AddButton/index.js
  src/components/Buttons/ArrowButton/ArrowButton.jsx
  src/components/Buttons/ArrowButton/index.js
Labels: 컴포넌트, 스타일

#59 💄 [유경] design : Post페이지의 ToggleButton hover 및 focus 디자인 수정
  src/pages/PostPage/Post.jsx
Labels: 페이지, 스타일

#62 ♻️ [유경] refactor : 불필요한 로직 제거 및 선택된 BackgroundType 버튼으로 확인 가능
  src/pages/PostPage/Post.jsx
  src/pages/PostPage/component/BackgroundOption/BackgroundOption.jsx
Labels: 기능, 페이지

#69 ✨ [유경] feat : post페이지 API연동 및 디자인 수정
  src/api/createRollingPaper.js
  src/components/Navbar.jsx
  src/pages/PostPage/Post.jsx
  src/pages/PostPage/component/BackgroundOption/BackgroundOption.jsx
Labels: 기능, 페이지
