Repository sprint4-team10/Rolling, pull requests merged in 2024-03, with the labels that each got.

#71 ♻️ [유경] refactor : 파일 삭제 및 컴포넌트 파일 분리
  src/components/Buttons/ButtonsStyled.js
  src/pages/PostPage/Post.jsx
  src/pages/PostPage/PostStyled.js
  src/pages/PostPage/component/BackgroundOption/BackgroundOption.jsx
  src/pages/PostPage/component/BackgroundOption/index.js
  src/pages/PostPage/component/CheckMark/CheckMark.jsx
  src/pages/PostPage/constant.js
Labels: 컴포넌트, 페이지

#72 :bug: [태진] fix: Senders 컴포넌트 마지막 ProfileList 너비 수정
  src/components/Senders/index.jsx
Labels: 오류

#75 ♻️[유경] refactor : Button 컴포넌트 반응형 추가
  src/components/Buttons/Buttons.jsx
  src/components/Buttons/ButtonsStyled.js
  src/pages/Main.jsx
Labels: 컴포넌트, 스타일

#79 🐛fix : conflict resolve
  src/components/Modal/Modal.jsx
  src/components/Modal/ModalStyled.jsx
  src/components/Modal/index.js
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/NavbarStyled.jsx
  src/components/Navbar/index.js
  src/components/PopOver/PopOver.jsx
  src/components/PopOver/index.js
  src/components/Portal/ModalPortal.jsx
  src/components/Portal/index.js
  src/components/Reaction/Reaction.jsx
  src/components/Reaction/ReactionStyled.jsx
  src/components/Reaction/index.js
  src/components/ReactionAddButton/ReactionAddButton.jsx
  src/components/ReactionAddButton/ReactionAddButtonStyled.jsx
  src/components/ReactionAddButton/index.js
  src/components/ReactionsPopOver/ReactionsPopOver.jsx
  src/components/ReactionsPopOver/ReactionsPopOverStyled.jsx
  src/components/ReactionsPopOver/index.js
  src/components/Senders/Senders.jsx
  src/components/Senders/index.js
  src/components/Senders/index.jsx
  src/components/Senders/sendersStyled.jsx
  src/components/SharePopOver/SharePopOver.jsx
  src/components/SharePopOver/SharePopOverStyled.jsx
  src/components/SharePopOver/index.js
  src/components/Toast/Toast.jsx
  src/components/Toast/ToastStyled.jsx
  src/components/Toast/index.js
  src/components/Toast/index.jsx
  src/components/deleteModal/deleteModal.jsx
  src/components/deleteModal/deleteModalStyled.jsx
  src/pages/Main.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/MainStyled.js
  src/pages/Main/index.js
  src/pages/Paper/Paper.jsx
  src/pages/Paper/components/CardList/CardList.jsx
  src/pages/Paper/components/CardList/CardListStyled.jsx
  src/pages/Paper/components/CardList/index.js
  src/pages/Paper/components/EditCard/EditCard.jsx
  src/pages/Paper/components/EditCard/EditCardStyled.jsx
  src/pages/Paper/components/EditCard/index.js
  src/pages/Paper/components/MessageCard/MessageCard.jsx
  src/pages/Paper/components/MessageCard/MessageCardStyled.jsx
  src/pages/Paper/components/MessageCard/index.js
  src/pages/Paper/components/PaperHeader/index.js
  src/pages/Paper/components/PaperHeader/paperHeader.jsx
  src/pages/Paper/components/PaperHeader/paperHeaderStyled.jsx
  src/pages/Paper/index.js
  src/pages/compononts/EditCard/EditCard.jsx
  src/pages/compononts/MessageCard/MessageCard.jsx
  src/pages/compononts/PaperHeader/index.jsx
Labels: 오류

#85 ✨ [유경] feat : post페이지 리퀘스트 중복 요청 방지
  src/pages/PostPage/Post.jsx
Labels: 기능, 페이지

#88 ♻️ [유경] refactor : post페이지 렌더링시, 에러메시지 출력되지 않도록 추가 및 ToggleButton 컴포넌트 분리 ...
  package-lock.json
  package.json
  src/components/Buttons/ToggleButton/ToggleButton.jsx
  src/components/Buttons/ToggleButton/ToggleButtonStyled.js
  src/components/Buttons/ToggleButton/index.js
  src/pages/PostPage/Post.jsx
  src/pages/PostPage/PostStyled.js
Labels: 컴포넌트, 페이지

#108 ♻️ [유경] refactor : Post페이지 컴포넌트 분리
  README.md
  public/_redirects
  src/App.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostStyled.js
  src/pages/Post/components/CheckMark/CheckMark.jsx
  src/pages/Post/components/CheckMark/CheckMarkStyled.js
  src/pages/Post/components/CheckMark/index.js
  src/pages/Post/components/PostDescription/PostDescription.jsx
  src/pages/Post/components/PostDescription/PostDescriptionStyled.js
  src/pages/Post/components/PostDescription/index.js
  src/pages/Post/components/PostInput/PostInput.jsx
  src/pages/Post/components/PostInput/PostInputStyled.js
  src/pages/Post/components/PostInput/index.js
  src/pages/Post/constant.js
  src/pages/Post/index.js
Labels: 컴포넌트, 페이지

#113 💄 [유경] design : favicon 및 페이지별 title 설정
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/index.jsx
  src/pages/List/List.jsx
  src/pages/Main/Main.jsx
  src/pages/Message/Message.jsx
  src/pages/Paper/Paper.jsx
  src/pages/Post/Post.jsx
Labels: 기능, 페이지, 스타일

#114 🐛 [유경] fix : post페이지 UX 개선 및 오류 해결
  src/pages/Post/PostStyled.js
  src/pages/Post/components/CheckMark/CheckMarkStyled.js
Labels: 페이지, 오류, 스타일
